import type { Metadata } from "next";
import { Inter, Inconsolata } from "next/font/google";
import "../globals.css";
import QueryProvider from "@/components/QueryProvider";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/layout/Header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const inconsolata = Inconsolata({
  variable: "--font-inconsolata",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <QueryProvider>
          <body className={`${inter.variable} ${inconsolata.variable}`}>
            <Header />
            <main className="mx-auto max-w-3xl p-4">{children}</main>
          </body>
        </QueryProvider>
      </html>
    </ClerkProvider>
  );
}
